- src: brianshumate.consul
  version: v2.2.0
- src: brianshumate.vault
  version: v2.1.0
- src: brianshumate.nomad
  version: v1.8.0
- src: kibatic.traefik
  version: 1.7.5
- src: geerlingguy.docker
  version: 2.5.2
- src: geerlingguy.java
  version: 1.9.5