---
- name: Install Nomad
  hosts: nomad
  any_errors_fatal: True
  become: True
  become_user: root
  roles:
    - role: brianshumate.nomad
  post_tasks:
    - consul:
        service_name: nomad
        service_port: 4646
        tags:
          - traefik.backend=nomad
          - traefik.frontend.rule=PathPrefix:/nomad